org.gradle.jvmargs=-Xmx2G
loom_version=1.17-SNAPSHOT
minecraft_version=26.1.2
loader_version=0.19.3
mod_version=0.2.2
maven_group=me.mrhikmen
archives_base_name=colorlight

fabric_version=0.155.2+26.1.2
modmenu_version=18.0.0
sodium_version=0.9.1+mc26.1.2
lambdynlights_version=4.11.0+26.1.2
java_version=25
