org.gradle.jvmargs=-Xmx2G
minecraft_version=1.21.1
loader_version=0.19.3
mod_version=0.2.0
maven_group=me.mrhikmen
archives_base_name=colorlight

fabric_version=0.116.14+1.21.1
java_version=21

modmenu_version=11.0.4
sodium_version=0.8.13-beta.1+mc1.21.1
lambdynlights_version=4.8.10+1.21.1

sable_version=2.0.3
sable_companion_version=1.6.0