org.gradle.jvmargs=-Xmx2G
loom_version=1.17-SNAPSHOT
minecraft_version=26.3
loader_version=0.19.5
mod_version=0.2.4
mod_test=1
maven_group=me.mrhikmen
archives_base_name=colorlight

fabric_version=0.161.0+26.3
modmenu_version=21.0.0
sodium_version=0.9.2+mc26.3
lambdynlights_version=4.13.0+26.3
java_version=25
